### ISSUE TITLE
This connects to the internet.

### ISSUE THREAD

**Issue by TeenageThrowawayV2** [JohnMHarrisJr/EasyIRC#1]
This connects to the internet. Make it run through TOR or be offline only.

Because honestly, sending headers and my IP address through this COULD reveal a LOT of information about me if my HTTP request is intercepted!

Also - Does this even use the system proxy?

**Comment by BrigDan** [comment]
I believe that using the internet to host your program exposes it to many viruses, I believe it should be passed around on USB sticks locally.

**Comment by BrigDan** [comment]
You should be able to connect to this program through DNS

**Comment by TeenageThrowawayV2** [comment]
I agree with @BrigDan

**Comment by JohnMHarrisJr** [comment]
This is not a real issue, closed.

**Comment by TeenageThrowawayV2** [comment]
Yeah it is a real issue. Come back.

**Comment by JohnMHarrisJr** [comment]
Locked.
