### ISSUE TITLE
Was not easy

### ISSUE THREAD

**Issue by SethDusek** [JohnMHarrisJr/EasyIRC#2]

**Comment by tirkaz** [comment]
nad halp pls

**Comment by BrigDan** [comment]
This program is missing the core function ability that I needed it for. Please fix this imminently.

**Comment by DigiTechs** [comment]
help i don't know what i'm doing where am i what is this

**Comment by BrigDan** [comment]
Its a program for hacking, quickly get off before the NSA blacklists you.

**Comment by DigiTechs** [comment]
oh okay i dont want that

bye now

**Comment by random-nick** [comment]
@BrigDan will this help me hack my friends facebook profile?

**Comment by TeenageThrowawayV2** [comment]
@random-nick Yep.

**Comment by JohnMHarrisJr** [comment]
Not a real issue. Closed and locked.
