### ISSUE TITLE
Doesn't run through Tor, and you keep ignoring my issue.

### ISSUE THREAD

**Issue by TeenageThrowawayV2** [JohnMHarrisJr/EasyIRC#6]
Dude, in the sake of security -- At least make it run through TOR over a secure connection ONLY

**Comment by TeenageThrowawayV2** [comment]
Or make it a .onion address that it connects through! That's an idea.

**Comment by JohnMHarrisJr** [comment]
When hosting this project, it can be used through Tor easily, requiring only a change to your Tor configuration files.
